name = "poze-scrisori"
main = "src/index.js"
compatibility_date = "2024-01-01"
account_id = "641cf08cdd9060470052c8887e987a60"

[[kv_namespaces]]
binding = "POZE"
id = "2bbf1dae6f394cfb932685ec2ab95b00"
